# This is used by the action https://github.com/dorny/paths-filter
dependencies: &dependencies
  - 'pyproject.toml'

python: &python
  - added|modified: 'src/**'
  - added|modified: 'tests/**'
  - 'manage.py'

changelog:
  - added|modified: 'changes/**'
  - 'CHANGELOG.md'

docs:
  - mkdocs.yml
  - added|modified: 'docs/**'
  - '.github/workflows/docs.yml'

mypy:
  - *python
  - 'mypy.ini'

run_tests:
  - *python
  - *dependencies
  - '.github/workflows/test.yml'
  - '.github/file-filters.yml'
  - tox.ini

lint:
  -  *python
  - 'pyproject.toml'
  - '.github/file-filters.yml'
  - '.github/workflows/lint.yml'
