import os
import tempfile

from smart_env import SmartEnv

DJANGO_HELP_BASE = "https://docs.djangoproject.com/en/5.2/ref/settings"


def setting(anchor: str) -> str:
    return f"@see {DJANGO_HELP_BASE}#{anchor}"


DEFAULTS = {
    "ADMIN_EMAIL": (str, "", "admin", True, "Initial user created at first deploy"),
    "ADMIN_PASSWORD": (str, "", "", True, "Password for initial user created at first deploy"),
    "AZURE_CLIENT_ID": (str, ""),
    "AZURE_CLIENT_SECRET": (str, ""),
    "AZURE_TENANT_KEY": (str, ""),
    "ALLOWED_HOSTS": (list, [], ["127.0.0.1", "localhost"], True, setting("allowed-hosts")),
    "ANYMAIL_IGNORE_RECIPIENT_STATUS": (
        bool,
        False,
        True,
        False,
        "If true, Anymail will not raise an AnymailRecipientStatus error for invalid or rejected recipient addresses.",
    ),
    "ANYMAIL_IGNORE_UNSUPPORTED_FEATURES": (
        bool,
        False,
        True,
        False,
        "If true, Anymail will ignore unsupported features silently.",
    ),
    "ANYMAIL_REQUESTS_TIMEOUT": (
        int,
        30,
        30,
        False,
        "Timeout in seconds for requests to the email service provider API.",
    ),
    "ANYMAIL_DEBUG_API_REQUESTS": (
        bool,
        False,
        True,
        False,
        "If true, Anymail will print the API requests to the console. Do not use in production.",
    ),
    "CELERY_BROKER_URL": (
        str,
        "redis://localhost:6379/2",
        "redis://localhost:6379/2",
        False,
        "URL of the message broker to use for Celery.",
    ),
    "CELERY_TASK_ALWAYS_EAGER": (
        bool,
        False,
        False,
        False,
        "If true, Celery tasks will be executed locally and synchronously. Used for testing.",
    ),
    "CONSTANCE_DATABASE_CACHE_BACKEND": (
        str,
        "",
        "",
        False,
        "The cache backend to use for caching the constance settings.",
    ),
    "CORS_ALLOWED_ORIGINS": (
        list,
        [],
        [],
        False,
        "A list of origins that are authorized to make cross-site HTTP requests.",
    ),
    "CSP_REPORT_ONLY": (bool, False, True, False, "If true, the CSP header will be in report-only mode."),
    "CSRF_COOKIE_NAME": (str, "hope_documents", "hope_documents", False, "The name of the CSRF cookie."),
    "CSRF_COOKIE_SECURE": (bool, True, False, False, "If true, the CSRF cookie will only be sent over HTTPS."),
    "CSRF_TRUSTED_ORIGINS": (list, [], [], False, "A list of trusted origins for unsafe requests (e.g. POST)."),
    "DATABASE_URL": (
        str,
        "psql://postgres:@127.0.0.1:5432/hope_documents",
        "psql://postgres:@127.0.0.1:5432/hope_documents",
        False,
        "The URL of the default database.",
    ),
    "DATABASE_HOPE_URL": (
        str,
        "psql://postgres:@127.0.0.1:5432/hope?options=-c%20default_transaction_read_only=on",
        "psql://postgres:@127.0.0.1:5432/hope?options=-c%20default_transaction_read_only=on",
        False,
        "The URL of the hope database.",
    ),
    "DEBUG": (bool, False, True, False, "If true, Django will be in debug mode."),
    "DEVELOPMENT": (bool, False, True, False, "If true, the application will be in development mode."),
    "EMAIL_BACKEND": (
        str,
        "django.core.mail.backends.smtp.EmailBackend",
        "django.core.mail.backends.console.EmailBackend",
        False,
        "The backend to use for sending emails.",
    ),
    "EMAIL_DEFAULT_SENDER": (
        str,
        "hope+noreply@unicef.org",
        "hope+noreply@unicef.org",
        False,
        "The default email address to use for sending emails.",
    ),
    "EMAIL_HOST": (str, "", "", False, "The host to use for sending email."),
    "EMAIL_HOST_PASSWORD": (str, "", "", False, "The password to use for sending email."),
    "EMAIL_HOST_USER": (str, "", "", False, "The username to use for sending email."),
    "EMAIL_PORT": (int, 587, 587, False, "The port to use for sending email."),
    "EMAIL_USE_TLS": (bool, True, True, False, "If true, TLS will be used for sending email."),
    "ENVIRONMENT": (str, "production", "develop", False, "The environment the application is running in."),
    "EXTRA_APPS": (list, [], [], False, "A list of extra apps to install."),
    "EXTRA_AUTHENTICATION_BACKENDS": (
        list,
        [],
        [],
        False,
        "A list of extra authentication backends to use.",
    ),
    "EXTRA_MIDDLEWARES": (list, [], [], False, "A list of extra middlewares to use."),
    "FILE_STORAGE_DEFAULT": (
        str,
        "django.core.files.storage.FileSystemStorage",
        "django.core.files.storage.FileSystemStorage",
        False,
        setting("storages"),
    ),
    "FILE_STORAGE_HOPE": (
        str,
        "django.core.files.storage.FileSystemStorage",
        "django.core.files.storage.FileSystemStorage",
        False,
        setting("storages"),
    ),
    "FILE_STORAGE_MEDIA": (
        str,
        "django.core.files.storage.FileSystemStorage",
        "django.core.files.storage.FileSystemStorage",
        False,
        setting("storages"),
    ),
    "FILE_STORAGE_STATIC": (
        str,
        "django.contrib.staticfiles.storage.StaticFilesStorage",
        "django.contrib.staticfiles.storage.StaticFilesStorage",
        False,
        setting("storages"),
    ),
    "GDAL_LIBRARY_PATH": (str, None, None, False, "The path to the GDAL library."),
    "GEOS_LIBRARY_PATH": (str, None, None, False, "The path to the GEOS library."),
    "LOGGING_LEVEL": (
        str,
        "CRITICAL",
        "DEBUG",
        False,
        "The logging level to use.",
    ),
    "LOGIN_LOCAL": (bool, True, True, False, "If true, local login will be enabled."),
    "LOGIN_SSO": (bool, True, True, False, "If true, SSO login will be enabled."),
    "MAILJET_API_URL": (
        str,
        "https://api.mailjet.com/v3.1/",
        "https://api.mailjet.com/v3.1/",
        False,
        "The URL of the Mailjet API.",
    ),
    "MAILJET_API_KEY": (str, "", "", False, "The API key for the Mailjet API."),
    "MAILJET_SECRET_KEY": (str, "", "", False, "The secret key for the Mailjet API."),
    "MEDIA_ROOT": (
        str,
        os.path.join(tempfile.gettempdir(), "hope_documents", "media"),
        os.path.join(tempfile.gettempdir(), "hope_documents", "media"),
        False,
        "The root directory for media files.",
    ),
    "OTP_VALIDITY_MINUTES": (int, 5, 5, False, "The validity of the OTP in minutes."),
    "REDIS_CACHE_URL": (
        str,
        "redis://localhost:6379/0",
        "redis://localhost:6379/0",
        False,
        "The URL of the Redis cache.",
    ),
    "REDIS_LOCK_URL": (
        str,
        "redis://localhost:6379/1?backend=django_redis.cache.RedisCache",
        "redis://localhost:6379/1?backend=django_redis.cache.RedisCache",
        False,
        "The URL of the Redis lock.",
    ),
    "REDIS_TSDB_URL": (
        str,
        "redis://localhost:6379/2",
        "redis://localhost:6379/2",
        False,
        "The URL of the Redis time series database.",
    ),
    "SECRET_KEY": (str, "", "", True, "The secret key for the application."),
    "SENTRY_DSN": (str, "", "", False, "The DSN for the Sentry project."),
    "SENTRY_ENVIRONMENT": (
        str,
        "",
        "",
        False,
        "The Sentry release environment tag (e.g. dev, stg, trn, prd).",
    ),
    "SESSION_COOKIE_SECURE": (
        bool,
        True,
        False,
        False,
        "If true, the session cookie will only be sent over HTTPS.",
    ),
    "SENTRY_ENABLED": (bool, False, False, False, "If true, Sentry will be enabled."),
    "STATIC_ROOT": (
        str,
        os.path.join(tempfile.gettempdir(), "hope_documents", "static"),
        os.path.join(tempfile.gettempdir(), "hope_documents", "static"),
        False,
        "The root directory for static files.",
    ),
    "STREAMING_BROKER_URL": (str, "", "", False, "The URL of the streaming broker."),
    "SUPERUSERS": (
        list,
        [],
        [],
        False,
        """A list of emails/or usernames that will automatically be granted superuser privileges
        ONLY the first time they are created. This is designed to be used in dev/qa environments deployed by CI,
        where the database can be empty.
        """,
    ),
    "TIME_ZONE": (str, "UTC", "UTC", False, "The timezone for the application."),
    "TWILIO_ACCOUNT_SID": (str, "", "", False, "The Twilio account SID."),
    "TWILIO_AUTH_TOKEN": (str, "", "", False, "The Twilio auth token."),
    "TWILIO_FROM_NUMBER": (str, "", "", False, "The Twilio from number."),
    "URL_PREFIX": (str, "", "", False, "The URL prefix for the application."),
}

env = SmartEnv(**DEFAULTS)
