# Generated by Django 5.2.7 on 2025-10-08 15:12

import django.db.models.deletion
import django_regex.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="archive.country")),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("match_regex", django_regex.fields.RegexField(default=".*")),
                ("number_regex", django_regex.fields.RegexField(default=".*")),
                ("type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="archive.documenttype")),
            ],
        ),
    ]
