# Generated by Django 5.2.7 on 2025-10-11 05:11

import django.core.validators
import django.db.models.deletion
import django_regex.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "code2",
                    models.CharField(
                        max_length=2, unique=True, validators=[django.core.validators.RegexValidator("^[A-Z]{2}$")]
                    ),
                ),
                (
                    "code3",
                    models.CharField(
                        max_length=3, unique=True, validators=[django.core.validators.RegexValidator("^[A-Z]{3}$")]
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=3, unique=True, validators=[django.core.validators.RegexValidator("^[0-9]{3}$")]
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        max_length=4, unique=True, validators=[django.core.validators.RegexValidator("^[A-Z]{3,4}$")]
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Document Types",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DocumentRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("match_regex", django_regex.fields.RegexField(default=".*")),
                ("number_regex", django_regex.fields.RegexField(default=".*")),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="archive.country")),
                ("type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="archive.documenttype")),
            ],
            options={
                "verbose_name_plural": "Document Rules",
                "ordering": ("country__name", "type__name"),
            },
        ),
    ]
