# Generated by Django 5.2.16 on 2026-09-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0002_alter_country_id_alter_documentrule_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("system", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="country",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="country",
            name="iso_code2",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="country",
            name="iso_code3",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="country",
            name="un_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(max_length=255)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="archive.country")),
                (
                    "document_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="archive.documenttype"),
                ),
            ],
            options={
                "ordering": ("document_type__name", "country__name", "version"),
                "unique_together": {("document_type", "country", "version")},
            },
        ),
        migrations.CreateModel(
            name="DocumentAttribute",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "region",
                    models.JSONField(
                        blank=True,
                        help_text='Bounding box, e.g. {"x": 10, "y": 20, "width": 100, "height": 50}',
                        null=True,
                    ),
                ),
                ("attribute", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="archive.attribute")),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="archive.document")),
            ],
            options={
                "ordering": ("document", "attribute__name"),
                "unique_together": {("document", "attribute")},
            },
        ),
    ]
