# Generated by Django 5.2.16 on 2026-09-29 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0002_alter_country_id_alter_documentrule_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for this extractable field.",
                        max_length=255,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of what this attribute represents.",
                        verbose_name="description",
                    ),
                ),
                (
                    "system",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Built-in system attributes (first_name, last_name, number) cannot be renamed or deleted."
                        ),
                        verbose_name="system",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="country",
            name="full_name",
            field=models.CharField(
                blank=True, help_text="Official full name of the country.", max_length=255, verbose_name="full_name"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="iso_code2",
            field=models.CharField(
                blank=True,
                help_text="Supplementary ISO 3166-1 alpha-2 two-letter code.",
                max_length=2,
                verbose_name="iso_code2",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="iso_code3",
            field=models.CharField(
                blank=True,
                help_text="Supplementary ISO 3166-1 alpha-3 three-letter code.",
                max_length=3,
                verbose_name="iso_code3",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="un_code",
            field=models.CharField(
                blank=True, help_text="Supplementary UN/numeric country code.", max_length=10, verbose_name="un_code"
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional human-readable description of this document type.",
                verbose_name="description",
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "version",
                    models.CharField(
                        help_text=(
                            "Free-text version label grouping the attribute set for this document type and country. "
                            "Can be a year (e.g. '2019') or an iteration label (e.g. 'v2')."
                        ),
                        max_length=255,
                        verbose_name="version",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="The country this document configuration applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        help_text="The type of document this configuration applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.documenttype",
                        verbose_name="document_type",
                    ),
                ),
            ],
            options={
                "ordering": ("document_type__name", "country__name", "version"),
                "unique_together": {("document_type", "country", "version")},
            },
        ),
        migrations.CreateModel(
            name="DocumentAttribute",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "region",
                    models.JSONField(
                        blank=True,
                        help_text='Bounding box, e.g. {"x": 10, "y": 20, "width": 100, "height": 50}',
                        null=True,
                        verbose_name="region",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        help_text="The extractable field from the Attributes catalog.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.attribute",
                        verbose_name="attribute",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document configuration this attribute belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.document",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "ordering": ("document", "attribute__name"),
                "unique_together": {("document", "attribute")},
            },
        ),
    ]
