name: "Documentation"

on:
  push:
    branches:
      - develop
    paths:
      - 'docs/**'
      - 'mkdocs.yaml'
      - './github/workflows/docs.yml'
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
    paths:
      - 'docs/**'
      - 'mkdocs.yaml'
      - './github/workflows/docs.yml'

#  schedule:
#    - cron: '37 23 * * 2'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    defaults:
      run:
        shell: bash
    outputs:
      docs: ${{ steps.changed_files.outputs.docs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: changed_files
        name: Check for file changes
        uses: dorny/paths-filter@v3
        with:
          base: ${{ github.ref }}
          token: ${{ github.token }}
          filters: .github/file-filters.yml
  generate:
    name: Generate
    if: needs.changes.outputs.docs == 'true'
    needs: changes
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install tox
      - name: Check Python Package structure
        run: tox -e docs -- -d docs-output

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs-output

  # Deployment job
  deploy:
    needs: generate
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
